version: '3.8'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION:-1.3.1.Final}
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    expose:
      - 2181
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION:-1.3.1.Final}
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    expose:
      - 9093
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    depends_on:
      - zookeeper
  postgres:
    image: debezium/postgres:9.6
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION:-1.3.1.Final}
    container_name: connect
    ports:
      - 8083:8083
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/es/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  es-data:
    driver: local

#  worker:
#    image: worker
#    depends_on:
#      - elasticsearch
#      - connect
#      - postgres
#      - kafka
#    ports:
#      - 8081:8081
#    expose:
#      - 8081
